service: notify-me

provider:
  name: aws
  region: eu-central-1
  runtime: nodejs12.x
  environment:
    NODE_ENV: dev
  apiGateway:
    # Enable gzip compression for responses > 1 KB
    minimumCompressionSize: 1024
    shouldStartNameWithService: true

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  # - serverless-plugin-chrome

# custom:
#   chrome:
#     flags:
#       - --window-size=1280,1696
#       - --hide-scrollbars
#       - --no-sandbox
#       - --auto-open-devtools-for-tabs
#       - --headless

package:
  exclude:
    - config/.env.stg
    - config/.env.pro
    - node_modules/puppeteer/.local-chromium/**
  include:
    - config/.env.dev

functions:
  notify:
    handler: src/handler.notify
    memorySize: 1536
    timeout: 30
    events:
      - http:
          path: notify
          method: get
