service: notify-me

provider:
  name: aws
  region: eu-central-1
  runtime: nodejs12.x
  environment:
    NODE_ENV: dev
  apiGateway:
    # Enable gzip compression for responses > 1 KB
    minimumCompressionSize: 1024
    shouldStartNameWithService: true

plugins:
  - serverless-plugin-typescript
  - serverless-offline

package:
  exclude:
    - node_modules/puppeteer/.local-chromium/**
  include:
    - config/.env

functions:
  notify:
    handler: src/handler.notify
    memorySize: 1536
    timeout: 30
    events:
      - schedule: rate(5 minutes)
      - http:
          path: notify
          method: get
