service: notify-me

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    # Enable gzip compression for responses > 1 KB
    minimumCompressionSize: 1024
    shouldStartNameWithService: true
  environment:
    NODE_ENV: dev

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-plugin-chrome

custom:
  chrome:
    flags:
      - --window-size=1280,1696
      - --hide-scrollbars
      - --no-sandbox
      - --auto-open-devtools-for-tabs
      - --headless

package:
  exclude:
    - config/.env.stg
    - config/.env.pro
    - node_modules/puppeteer/.local-chromium/**
  include:
    - config/.env.dev

functions:
  notify:
    handler: src/handler.notify
    memorySize: 1536
    timeout: 30
    events:
      - http:
          path: notify
          method: get
