service: notify-me

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-offline
  - serverless-plugin-chrome
  - serverless-webpack

package:
  exclude:
    - node_modules/puppeteer/.local-chromium/**

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
    shouldStartNameWithService: true
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  notify:
    handler: handler.notify
    memorySize: 1536
    timeout: 30
    events:
      - http:
          method: get
          path: /notify
